# Proyecto análisis de conversación de mensajería

## Cargar datos
- Exportar una conversación personal o grupal de Whastapp o Telegram en un formato adecuado (JSON, CSV, etc), no exportar audios, archivos multimedia, etc
- Importar archivo y convertirlo en dataframe
- Obtener y graficar los siguientes datos. Elegir el gráfico que mejor represente los datos

In [423]:
import json
import pandas as pd
import numpy as np
import requests
import os, sys
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import dateutil


bd2 = open('../data/result.json', encoding='utf8')
data = json.load(bd2)


msgs = data['messages']
df = pd.DataFrame(msgs)

df = df.filter(items = ['id','date', 'from', 'reply_to_message_id' ,'text'])
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")
df

,id,date,from,reply_to_message_id,text
0,21639,2021-08-09 17:34:53,NaN,NaN,
1,21647,2021-08-09 17:36:48,Augusto Missino,NaN,Alguno quedó sin grupo?
2,21648,2021-08-09 17:36:51,Lautaro G,NaN,Grupo: giancarlo y lautaro
3,21652,2021-08-09 17:37:47,Lucas Galdame Villegas,NaN,"Grupo: Lucas g\nGaldame, Gaston Fenske y Danie..."
4,21656,2021-08-09 17:38:16,Julián,NaN,Grupo: Delfina Quinteros y Julián Navarrete
5,21657,2021-08-09 17:38:18,Emiliano Muñoz,21647.0,Estamos con lucas ollarce por si queres ser co...
6,21659,2021-08-09 17:38:53,NaN,NaN,
7,21665,2021-08-09 17:40:43,Augusto Missino,21657.0,Bueno
8,21674,2021-08-09 17:41:08,Delfina Quinteros,21656.0,si alguien todavia no tiene grupo puede ser co...
9,21677,2021-08-09 17:41:35,Emiliano Muñoz,NaN,"Grupo: Emiliano, Lucas Ollarce, Augusto"
10,21681,2021-08-09 17:43:12,Danilo Verardo,NaN,"Grupo: Arenas Douglas, Fernández Enzo, Cerna V..."
11,21682,2021-08-09 17:43:49,Lucas Galdame Villegas,21652.0,Profe sume a gaston
12,21683,2021-08-09 17:44:10,Santiago Moyano,NaN,"Grupo: Bruno Romero, Santiago Moyano"
13,21685,2021-08-09 17:45:04,NaN,NaN,
14,21686,2021-08-09 17:45:15,Lucas Galdame Villegas,21682.0,Fenske
15,21688,2021-08-09 17:48:53,Douglas,21681.0,Profe este grupo lo puso?
16,21690,2021-08-09 17:53:20,Andrea Navarro (juncotic.com),NaN,Usuario github: AndreaNavarroMoreno
17,21693,2021-08-09 17:53:46,Andrea Navarro (juncotic.com),NaN,Usuario gitlab: andrea.navarro
18,21702,2021-08-09 17:57:08,Fede Pardo,NaN,.
19,21724,2021-08-09 18:01:27,NaN,NaN,
20,26942,2021-08-30 18:15:46,Gabriel Arenas 🇦🇷,NaN,[chicos por favor pasen a este enlace Clases D...
21,26952,2021-08-30 18:26:55,NaN,NaN,
22,28275,2021-09-06 09:58:18,Gabriel Arenas 🇦🇷,NaN,"Estimados alumnos, el cuestionario sobre data..."
23,28280,2021-09-06 10:13:38,Tato Beato,NaN,Genial profe
24,28337,2021-09-06 12:44:15,Pariente,NaN,Bueno profe
25,28382,2021-09-06 15:09:05,Ramiro Alberto Giandinoto,NaN,Gravias Profe
26,28654,2021-09-06 18:08:51,Gabriel Arenas 🇦🇷,NaN,"Chicos, 18:30 iniciamos el meet"
27,28655,2021-09-06 18:09:01,Giancarlo,28654.0,perfecto
28,28673,2021-09-06 18:19:03,Lucas Galdame Villegas,NaN,mismo link del otro dia??
29,28696,2021-09-06 18:33:23,Gabriel Arenas 🇦🇷,NaN,"Correcto, mismo link"
30,28700,2021-09-06 18:37:41,Doki,NaN,"[{'type': 'email', 'text': 's.martinez@alumno...."
31,28702,2021-09-06 18:37:51,Giancarlo,NaN,"[{'type': 'email', 'text': 'g.galvarini@alumno..."
32,28703,2021-09-06 18:37:55,Bruno,NaN,"[{'type': 'email', 'text': 'b.romero@alumno.um..."
33,28704,2021-09-06 18:38:00,Seba Fernandez,NaN,"[{'type': 'email', 'text': 's.fernandez@alumno..."
34,28705,2021-09-06 18:38:10,Delfina Quinteros,NaN,"[{'type': 'email', 'text': 'de.quinteros@alumn..."
35,28706,2021-09-06 18:38:10,Ramiro Alberto Giandinoto,NaN,"[{'type': 'email', 'text': 'r.giandinoto@alumn..."
36,28707,2021-09-06 18:38:16,Tato Beato,NaN,"[{'type': 'email', 'text': 'd.beato@alumno.um...."
37,28708,2021-09-06 18:38:20,Lucas Galdame Villegas,NaN,"[{'type': 'email', 'text': 'l.galdame@alumno.u..."
38,28709,2021-09-06 18:38:21,Matias,NaN,"[{'type': 'email', 'text': 'm.quevedo@alumno.u..."
39,28710,2021-09-06 18:38:29,Santi Riera,NaN,"[{'type': 'email', 'text': 's.riera@alumno.um...."
40,28711,2021-09-06 18:38:30,Lautaro G,NaN,"[{'type': 'email', 'text': 'fl.gimenez@alumno...."
41,28712,2021-09-06 18:38:35,Pariente,NaN,"[{'type': 'email', 'text': 'y.maureira@alumno...."
42,28713,2021-09-06 18:38:52,Santiago Moyano,NaN,"[{'type': 'email', 'text': 's.moyano@alumno.um..."
43,28715,2021-09-06 18:39:01,Lucas Ollarce,NaN,"[{'type': 'email', 'text': 'l.ollarce@alumno.u..."
44,28716,2021-09-06 18:39:22,Julián,NaN,"[{'type': 'email', 'text': 'j.navarrete@alumno..."
45,28719,2021-09-06 18:39:50,Nico Olivares,NaN,"[{'type': 'email', 'text': 'n.olivares@alumno...."
46,28723,2021-09-06 18:42:57,jose Ruti,NaN,"[{'type': 'email', 'text': 'j.ruti@alumno.um.e..."
47,28744,2021-09-06 19:04:47,Fede Pardo,NaN,"[{'type': 'email', 'text': 'f.pardo@alumno.um...."
48,28745,2021-09-06 19:05:12,Douglas,NaN,"[{'type': 'email', 'text': 'd.arenas@alumno.um..."
49,28746,2021-09-06 19:05:49,Augusto Missino,NaN,"[{'type': 'email', 'text': 'a.misino@alumno.um..."
50,28747,2021-09-06 19:07:12,Emiliano Muñoz,NaN,"[{'type': 'email', 'text': 'e.munoz@alumno.um...."
51,28748,2021-09-06 19:07:21,Enzo Fernandez,NaN,"[{'type': 'email', 'text': 'evm.fernandez@alum..."
52,28753,2021-09-06 19:09:07,Facu Luna,NaN,"[{'type': 'email', 'text': 'f.luna@alumno.um.e..."

### Cantidad de mensajes enviados por cada usuario

In [424]:
df_msg = df.groupby('from')['text'].count()

df_msg

from
Andrea Navarro (juncotic.com)    2
Augusto Missino                  3
Bruno                            1
Danilo Verardo                   1
Delfina Quinteros                2
Doki                             1
Douglas                          2
Emiliano Muñoz                   3
Enzo Fernandez                   1
Facu Luna                        1
Fede Pardo                       2
Gabriel Arenas 🇦🇷                4
Giancarlo                        2
Julián                           2
Lautaro G                        2
Lucas Galdame Villegas           5
Lucas Ollarce                    1
Matias                           1
Nico Olivares                    1
Pariente                         2
Ramiro Alberto Giandinoto        2
Santi Riera                      1
Santiago Moyano                  2
Seba Fernandez                   1
Tato Beato                       2
jose Ruti                        1
Name: text, dtype: int64

### Promedio de palabras utilizadas por mensaje por cada usuario

In [425]:
df_text = df['text']
quantity = 0
content = ''
for item in df_text:
    if not item == '':
        if type(item) == list:
            if type(item[0]) == dict:
                content = item[0]['text']
                quantity += 1
        else:
            content = item.split(' ')
            quantity += len(content)
        
print(f'Cantidad de palabras: {quantity}')
total_msg = df_msg.sum()
print(f'Cantidad de mensajes: {total_msg}')

total = quantity/total_msg
print(f'Se ulilizaron un promedio de: {total} palabras por mensaje.')

df.groupby('from')['text'].count() * total

Cantidad de palabras: 138
Cantidad de mensajes: 48
Se ulilizaron un promedio de: 2.875 palabras por mensaje.

from
Andrea Navarro (juncotic.com)     5.750
Augusto Missino                   8.625
Bruno                             2.875
Danilo Verardo                    2.875
Delfina Quinteros                 5.750
Doki                              2.875
Douglas                           5.750
Emiliano Muñoz                    8.625
Enzo Fernandez                    2.875
Facu Luna                         2.875
Fede Pardo                        5.750
Gabriel Arenas 🇦🇷                11.500
Giancarlo                         5.750
Julián                            5.750
Lautaro G                         5.750
Lucas Galdame Villegas           14.375
Lucas Ollarce                     2.875
Matias                            2.875
Nico Olivares                     2.875
Pariente                          5.750
Ramiro Alberto Giandinoto         5.750
Santi Riera                       2.875
Santiago Moyano                   5.750
Seba Fernandez                    2.875
Tato Beato                        5.750
jose Ruti                         2.875
Name: text, dtype: float64

### Porcentaje de mensajes enviados por cada usuario

In [426]:
percentage = (df.groupby('from')['text'].count() / total_msg) * 100
percentage

from
Andrea Navarro (juncotic.com)     4.166667
Augusto Missino                   6.250000
Bruno                             2.083333
Danilo Verardo                    2.083333
Delfina Quinteros                 4.166667
Doki                              2.083333
Douglas                           4.166667
Emiliano Muñoz                    6.250000
Enzo Fernandez                    2.083333
Facu Luna                         2.083333
Fede Pardo                        4.166667
Gabriel Arenas 🇦🇷                 8.333333
Giancarlo                         4.166667
Julián                            4.166667
Lautaro G                         4.166667
Lucas Galdame Villegas           10.416667
Lucas Ollarce                     2.083333
Matias                            2.083333
Nico Olivares                     2.083333
Pariente                          4.166667
Ramiro Alberto Giandinoto         4.166667
Santi Riera                       2.083333
Santiago Moyano                   4.166667
Seba Fernandez                    2.083333
Tato Beato                        4.166667
jose Ruti                         2.083333
Name: text, dtype: float64

### Frecuencia de envío de mensaje dependiendo la hora del día

In [427]:
groups = [df['date'].dt.to_period('h')]
agregations = {
         'text':["count"] 
            }
df.groupby(groups).agg(agregations)

                  text
                 count
date
2021-08-09 17:00    19
2021-08-09 18:00     1
2021-08-30 18:00     2
2021-09-06 09:00     1
2021-09-06 10:00     1
2021-09-06 12:00     1
2021-09-06 15:00     1
2021-09-06 18:00    21
2021-09-06 19:00     6

### Frecuencia de envío de mensaje dependiendo del día de la semana

In [428]:
day = [df['date'].dt.weekday]
agregations = {
         'text':"count" 
            }
df.groupby(day).agg(agregations)

      text
date
0       53

Todos los mensajes fueron enviados el mismo dia de la semana que fue el dia lunes por eso nos representa que todos los mensajes enviados fueron el mismo dia.

### Hora del día preferida por cada usuario para enviar mensajes

In [429]:
groups = [df['date'].dt.to_period('h'),"from"]
agregations = {
         'text':'count' 
            }
df.groupby( groups).agg(agregations)

                                                text
date             from
2021-08-09 17:00 Andrea Navarro (juncotic.com)     2
                 Augusto Missino                   2
                 Danilo Verardo                    1
                 Delfina Quinteros                 1
                 Douglas                           1
                 Emiliano Muñoz                    2
                 Fede Pardo                        1
                 Julián                            1
                 Lautaro G                         1
                 Lucas Galdame Villegas            3
                 Santiago Moyano                   1
2021-08-30 18:00 Gabriel Arenas 🇦🇷                 1
2021-09-06 09:00 Gabriel Arenas 🇦🇷                 1
2021-09-06 10:00 Tato Beato                        1
2021-09-06 12:00 Pariente                          1
2021-09-06 15:00 Ramiro Alberto Giandinoto         1
2021-09-06 18:00 Bruno                             1
                 Delfina Quinteros                 1
                 Doki                              1
                 Gabriel Arenas 🇦🇷                 2
                 Giancarlo                         2
                 Julián                            1
                 Lautaro G                         1
                 Lucas Galdame Villegas            2
                 Lucas Ollarce                     1
                 Matias                            1
                 Nico Olivares                     1
                 Pariente                          1
                 Ramiro Alberto Giandinoto         1
                 Santi Riera                       1
                 Santiago Moyano                   1
                 Seba Fernandez                    1
                 Tato Beato                        1
                 jose Ruti                         1
2021-09-06 19:00 Augusto Missino                   1
                 Douglas                           1
                 Emiliano Muñoz                    1
                 Enzo Fernandez                    1
                 Facu Luna                         1
                 Fede Pardo                        1

Las horas preferida por los integrantes es a las 17 horas, 18 horas y se podria considerar tambien a partir de las 19 horas

### Día de la semana preferida por cada usuario para enviar mensajes

In [430]:
groups = [df['date'].dt.to_period('w'),"from"]
agregations = {
         'text': "count" 
            }
df.groupby( groups).agg(agregations)

                                                     text
date                  from
2021-08-09/2021-08-15 Andrea Navarro (juncotic.com)     2
                      Augusto Missino                   2
                      Danilo Verardo                    1
                      Delfina Quinteros                 1
                      Douglas                           1
                      Emiliano Muñoz                    2
                      Fede Pardo                        1
                      Julián                            1
                      Lautaro G                         1
                      Lucas Galdame Villegas            3
                      Santiago Moyano                   1
2021-08-30/2021-09-05 Gabriel Arenas 🇦🇷                 1
2021-09-06/2021-09-12 Augusto Missino                   1
                      Bruno                             1
                      Delfina Quinteros                 1
                      Doki                              1
                      Douglas                           1
                      Emiliano Muñoz                    1
                      Enzo Fernandez                    1
                      Facu Luna                         1
                      Fede Pardo                        1
                      Gabriel Arenas 🇦🇷                 3
                      Giancarlo                         2
                      Julián                            1
                      Lautaro G                         1
                      Lucas Galdame Villegas            2
                      Lucas Ollarce                     1
                      Matias                            1
                      Nico Olivares                     1
                      Pariente                          2
                      Ramiro Alberto Giandinoto         2
                      Santi Riera                       1
                      Santiago Moyano                   1
                      Seba Fernandez                    1
                      Tato Beato                        2
                      jose Ruti                         1

### Cantidad promedio de mensajes enviados por hora para cada usuario

In [431]:
groups = [df['date'].dt.to_period('h'),"from"]
agregations = {
         'text': ["count"]
            }
df.groupby(groups).agg(agregations)

                                                text
                                               count
date             from
2021-08-09 17:00 Andrea Navarro (juncotic.com)     2
                 Augusto Missino                   2
                 Danilo Verardo                    1
                 Delfina Quinteros                 1
                 Douglas                           1
                 Emiliano Muñoz                    2
                 Fede Pardo                        1
                 Julián                            1
                 Lautaro G                         1
                 Lucas Galdame Villegas            3
                 Santiago Moyano                   1
2021-08-30 18:00 Gabriel Arenas 🇦🇷                 1
2021-09-06 09:00 Gabriel Arenas 🇦🇷                 1
2021-09-06 10:00 Tato Beato                        1
2021-09-06 12:00 Pariente                          1
2021-09-06 15:00 Ramiro Alberto Giandinoto         1
2021-09-06 18:00 Bruno                             1
                 Delfina Quinteros                 1
                 Doki                              1
                 Gabriel Arenas 🇦🇷                 2
                 Giancarlo                         2
                 Julián                            1
                 Lautaro G                         1
                 Lucas Galdame Villegas            2
                 Lucas Ollarce                     1
                 Matias                            1
                 Nico Olivares                     1
                 Pariente                          1
                 Ramiro Alberto Giandinoto         1
                 Santi Riera                       1
                 Santiago Moyano                   1
                 Seba Fernandez                    1
                 Tato Beato                        1
                 jose Ruti                         1
2021-09-06 19:00 Augusto Missino                   1
                 Douglas                           1
                 Emiliano Muñoz                    1
                 Enzo Fernandez                    1
                 Facu Luna                         1
                 Fede Pardo                        1

### Cantidad de usuarios promedio que envían mensaje por cada día de la semana

In [432]:
groups = [df['date'].dt.weekday, 'from']
agregations = {
         'text':["count"] 
            }
df.groupby( groups).agg(agregations)

                                    text
                                   count
date from
0    Andrea Navarro (juncotic.com)     2
     Augusto Missino                   3
     Bruno                             1
     Danilo Verardo                    1
     Delfina Quinteros                 2
     Doki                              1
     Douglas                           2
     Emiliano Muñoz                    3
     Enzo Fernandez                    1
     Facu Luna                         1
     Fede Pardo                        2
     Gabriel Arenas 🇦🇷                 4
     Giancarlo                         2
     Julián                            2
     Lautaro G                         2
     Lucas Galdame Villegas            5
     Lucas Ollarce                     1
     Matias                            1
     Nico Olivares                     1
     Pariente                          2
     Ramiro Alberto Giandinoto         2
     Santi Riera                       1
     Santiago Moyano                   2
     Seba Fernandez                    1
     Tato Beato                        2
     jose Ruti                         1

### Cantidad de mensajes envíados por mes

In [433]:
groups = [df['date'].dt.to_period('m'),"from"]
agregations = {
         'text': "count" 
            }
df.groupby(groups).agg(agregations)

                                       text
date    from
2021-08 Andrea Navarro (juncotic.com)     2
        Augusto Missino                   2
        Danilo Verardo                    1
        Delfina Quinteros                 1
        Douglas                           1
        Emiliano Muñoz                    2
        Fede Pardo                        1
        Gabriel Arenas 🇦🇷                 1
        Julián                            1
        Lautaro G                         1
        Lucas Galdame Villegas            3
        Santiago Moyano                   1
2021-09 Augusto Missino                   1
        Bruno                             1
        Delfina Quinteros                 1
        Doki                              1
        Douglas                           1
        Emiliano Muñoz                    1
        Enzo Fernandez                    1
        Facu Luna                         1
        Fede Pardo                        1
        Gabriel Arenas 🇦🇷                 3
        Giancarlo                         2
        Julián                            1
        Lautaro G                         1
        Lucas Galdame Villegas            2
        Lucas Ollarce                     1
        Matias                            1
        Nico Olivares                     1
        Pariente                          2
        Ramiro Alberto Giandinoto         2
        Santi Riera                       1
        Santiago Moyano                   1
        Seba Fernandez                    1
        Tato Beato                        2
        jose Ruti                         1

### Cantidad mínima, máxima y promedio de palabras por mensaje

In [445]:
df_text = df['text']
content = ''
max_size_text = []
words_max = 0
quantity_total = 0
for item in df_text:
    quantity = 0
    if not item == '':
        if type(item) == list:
            if type(item[0]) == dict:
                content = item[0]['text']
                quantity += 1
                quantity_total += quantity
                print(f'{content} | Palabras: {quantity}')
        else:
            content = item.split(' ')
            quantity += len(content)
            quantity_total += quantity
            print(f'{content} | Palabras: {quantity}')
            words_max_aux = len(content)
            if words_max < words_max_aux:
                words_max = words_max_aux
                max_size_text = content

print(f'Texto con el (Maximo) de palabras: {max_size_text}, Contiene: {words_max} palabras.')
total = quantity_total/df_msg.sum()
print(f'Se ulilizaron un promedio de: {total} palabras por mensaje.')

['Alguno', 'quedó', 'sin', 'grupo?'] | Palabras: 4
['Grupo:', 'giancarlo', 'y', 'lautaro'] | Palabras: 4
['Grupo:', 'Lucas', 'g\nGaldame,', 'Gaston', 'Fenske', 'y', 'Daniel', 'Beato'] | Palabras: 8
['Grupo:', 'Delfina', 'Quinteros', 'y', 'Julián', 'Navarrete'] | Palabras: 6
['Estamos', 'con', 'lucas', 'ollarce', 'por', 'si', 'queres', 'ser', 'con', 'nosotros'] | Palabras: 10
['Bueno'] | Palabras: 1
['si', 'alguien', 'todavia', 'no', 'tiene', 'grupo', 'puede', 'ser', 'con', 'nosotros'] | Palabras: 10
['Grupo:', 'Emiliano,', 'Lucas', 'Ollarce,', 'Augusto'] | Palabras: 5
['Grupo:', 'Arenas', 'Douglas,', 'Fernández', 'Enzo,', 'Cerna', 'Verardo', 'Danilo'] | Palabras: 8
['Profe', 'sume', 'a', 'gaston'] | Palabras: 4
['Grupo:', 'Bruno', 'Romero,', 'Santiago', 'Moyano'] | Palabras: 5
['Fenske'] | Palabras: 1
['Profe', 'este', 'grupo', 'lo', 'puso?'] | Palabras: 5
['Usuario', 'github:', 'AndreaNavarroMoreno'] | Palabras: 3
['Usuario', 'gitlab:', 'andrea.navarro'] | Palabras: 3
['.'] | Palabras: 1
['Estimados', 'alumnos,', '', 'el', 'cuestionario', 'sobre', 'datawarehouse', 'lo', 'paso', 'al', 'lunes', 'después', 'de', 'las', 'mesas', '(20/09/2021)'] | Palabras: 16
['Genial', 'profe'] | Palabras: 2
['Bueno', 'profe'] | Palabras: 2
['Gravias', 'Profe'] | Palabras: 2
['Chicos,', '', '18:30', 'iniciamos', 'el', 'meet'] | Palabras: 6
['perfecto'] | Palabras: 1
['mismo', 'link', 'del', 'otro', 'dia??'] | Palabras: 5
['Correcto,', 'mismo', 'link'] | Palabras: 3
s.martinez@alumno.um.edu.ar | Palabras: 1
g.galvarini@alumno.um.edu.ar | Palabras: 1
b.romero@alumno.um.edu.ar | Palabras: 1
s.fernandez@alumno.um.edu.ar | Palabras: 1
de.quinteros@alumno.um.edu.ar | Palabras: 1
r.giandinoto@alumno.um.edu.ar | Palabras: 1
d.beato@alumno.um.edu.ar | Palabras: 1
l.galdame@alumno.um.edu.ar | Palabras: 1
m.quevedo@alumno.um.edu.ar | Palabras: 1
s.riera@alumno.um.edu.ar | Palabras: 1
fl.gimenez@alumno.um.edu.ar | Palabras: 1
y.maureira@alumno.um.edu.ar | Palabras: 1
s.moyano@alumno.um.edu.ar | Palabras: 1
l.ollarce@alumno.um.edu.ar | Palabras: 1
j.navarrete@alumno.um.edu.ar | Palabras: 1
n.olivares@alumno.um.edu.ar | Palabras: 1
j.ruti@alumno.um.edu.ar | Palabras: 1
f.pardo@alumno.um.edu.ar | Palabras: 1
d.arenas@alumno.um.edu.ar | Palabras: 1
a.misino@alumno.um.edu.ar | Palabras: 1
e.munoz@alumno.um.edu.ar | Palabras: 1
evm.fernandez@alumno.um.edu.ar | Palabras: 1
f.luna@alumno.um.edu.ar | Palabras: 1
Texto con el (Maximo) de palabras: ['Estimados', 'alumnos,', '', 'el', 'cuestionario', 'sobre', 'datawarehouse', 'lo', 'paso', 'al', 'lunes', 'después', 'de', 'las', 'mesas', '(20/09/2021)'], Contiene: 16 palabras.
Se ulilizaron un promedio de: 2.875 palabras por mensaje.